/* Write your PL/SQL query statement below */
SELECT DISTINCT NUM AS CONSECUTIVENUMS FROM(
    SELECT NUM,
    LEAD(NUM,1) OVER (ORDER BY ID)AS NEXT1,
    LEAD(NUM,2) OVER(ORDER BY ID ) AS NEXT2
    FROM LOGS
)T
WHERE NUM = NEXT1 AND NUM =NEXT2;