/* Write your PL/SQL query statement below */
SELECT P.FIRSTNAME,P.LASTNAME,A.CITY,A.STATE
FROM PERSON P,ADDRESS A
WHERE P.PERSONID=A.PERSONID
UNION
SELECT P.FIRSTNAME,P.LASTNAME,NULL,NULL
FROM PERSON P
WHERE P.PERSONID NOT IN(SELECT PERSONID FROM ADDRESS);

